FROM vanessa/slurm:18.08.6

# This container will be built on docker-compose up -d

RUN pip install numpy==1.12 && pip install websockify

RUN yum install -y nc && \
    wget https://turbovnc.org/pmwiki/uploads/Downloads/TurboVNC.repo && \
    mv TurboVNC.repo /etc/yum.repos.d/ && \
    yum install -y turbovnc


# Install for Rstudio App
COPY apps/RStudio/install-compute-dependencies.sh /install-rstudio.sh
RUN /bin/bash /install-rstudio.sh
